---
language: python
services: docker

env:
  global:
    - ROLE_NAME: selinux
  matrix:
    - MOLECULE_DISTRO: centos7
    - MOLECULE_DISTRO: centos6

install:
  - pip install molecule docker

before_script:
  - cd ../
  - mv ansible-$ROLE_NAME blackstar257.$ROLE_NAME
  - cd blackstar257.$ROLE_NAME

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
