---
- name: Include variables for specific OS
  ansible.builtin.include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family in ['RedHat']
  tags: ["selinux"]

- name: Include RedHat/CentOS/Rocky/Alma tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_os_family == "RedHat"
  tags: ["selinux"]

- name: Include Fedora tasks
  ansible.builtin.include_tasks: rhel.yml
  when: ansible_distribution == "Fedora"
  tags: ["selinux"]
