- name: Verify
  hosts: all
  gather_facts: true
  tasks:
    - name: Check SELinux status
      ansible.builtin.command: getenforce
      register: selinux_status
      changed_when: false
      failed_when: false
    - name: Verify SELinux state
      ansible.builtin.assert:
        that:
          - selinux_status.stdout in ['Enforcing', 'Permissive', 'Disabled']
        fail_msg: "SELinux is not in a valid state"
        success_msg: "SELinux is properly configured"
    - name: Check SELinux configuration file
      ansible.builtin.stat:
        path: /etc/selinux/config
      register: selinux_config
    - name: Verify SELinux config file exists
      ansible.builtin.assert:
        that:
          - selinux_config.stat.exists
        fail_msg: "SELinux configuration file does not exist"
        success_msg: "SELinux configuration file exists"
    - name: Check if autorelabel file exists when expected
      ansible.builtin.stat:
        path: /.autorelabel
      register: autorelabel_file
      when: selinux_relabel | default(true) | bool
    - name: Display SELinux information
      ansible.builtin.debug:
        msg:
          - "SELinux status: {{ selinux_status.stdout }}"
          - "SELinux config exists: {{ selinux_config.stat.exists }}"
          - "Autorelabel file exists: {{ autorelabel_file.stat.exists | default('N/A') }}"
